- name: populate /root/.bashrc
  lineinfile:
    dest: "/root/.bashrc"
    state: present
    regexp: "^{{ item.key }}="
    line: "{{ item.key }}={{ item.value}}"
  with_items: "{{ os_environment }}"
